In [6]:
# Импорт библиотек
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
pd.set_option('display.max_columns', None)
df = pd.read_csv("/home/savely/ds_bootcamp/Final_project-boevue_susliki/data/_data.csv", index_col='Unnamed: 0')
df.head(3)

,ID объявления,Количество комнат,Тип,Метро,Адрес,"Площадь, м2",Дом,Парковка,Цена,Телефоны,Описание,Ремонт,"Площадь комнат, м2",Балкон,Окна,Санузел,Можно с детьми/животными,Дополнительно,Название ЖК,Серия дома,"Высота потолков, м",Лифт,Мусоропровод,Ссылка на объявление
0,271271157,4,Квартира,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0/20.0,"5/16, Монолитный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79166369231,Без комиссии для нанимателя! Бонус коллегам 12...,Дизайнерский,NaN,NaN,NaN,NaN,"Можно с детьми, Можно с животными","Мебель в комнатах, Мебель на кухне, Ванна, Душ...","Новый Арбат, 2010",NaN,3.0,"Пасс (4), Груз (1)",Да,https://www.cian.ru/rent/flat/271271157
1,271634126,4,Квартира,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0/95.0/18.0,"5/16, Монолитно-кирпичный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79850608590,Лот 93107. Елена Анисимова.\n\nБонус агенту 50...,Дизайнерский,25 25 20 25,NaN,На улицу и двор,"Совмещенный (2), Раздельный (1)",Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.5,"Пасс (1), Груз (1)",Нет,https://www.cian.ru/rent/flat/271634126
2,271173086,"4, Оба варианта",Квартира,м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0/116.0/4.0,5/16,подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...","+79672086536, +79099269384","ID 36380: Шикарная 4-х км. квартира в ЖК ""Нов...",Евроремонт,NaN,NaN,На улицу и двор,Совмещенный (3),Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.2,Пасс (1),NaN,https://www.cian.ru/rent/flat/271173086

### Удаление столбцов из датафрейма

In [8]:
df.drop(["Тип", "Телефоны", "Описание", "Дополнительно", "Название ЖК", "Серия дома", "Ссылка на объявление"], axis=1, inplace=True)
df.head(3)

,ID объявления,Количество комнат,Метро,Адрес,"Площадь, м2",Дом,Парковка,Цена,Ремонт,"Площадь комнат, м2",Балкон,Окна,Санузел,Можно с детьми/животными,"Высота потолков, м",Лифт,Мусоропровод
0,271271157,4,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0/20.0,"5/16, Монолитный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",Дизайнерский,NaN,NaN,NaN,NaN,"Можно с детьми, Можно с животными",3.0,"Пасс (4), Груз (1)",Да
1,271634126,4,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0/95.0/18.0,"5/16, Монолитно-кирпичный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",Дизайнерский,25 25 20 25,NaN,На улицу и двор,"Совмещенный (2), Раздельный (1)",Можно с детьми,3.5,"Пасс (1), Груз (1)",Нет
2,271173086,"4, Оба варианта",м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0/116.0/4.0,5/16,подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",Евроремонт,NaN,NaN,На улицу и двор,Совмещенный (3),Можно с детьми,3.2,Пасс (1),NaN

#### Оставляем строки, которые относятся только к городу Москва

In [9]:
df = df[df["Адрес"].str.contains("Москва", case=False, na=False)]
df.head(3)

,ID объявления,Количество комнат,Метро,Адрес,"Площадь, м2",Дом,Парковка,Цена,Ремонт,"Площадь комнат, м2",Балкон,Окна,Санузел,Можно с детьми/животными,"Высота потолков, м",Лифт,Мусоропровод
0,271271157,4,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0/20.0,"5/16, Монолитный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",Дизайнерский,NaN,NaN,NaN,NaN,"Можно с детьми, Можно с животными",3.0,"Пасс (4), Груз (1)",Да
1,271634126,4,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0/95.0/18.0,"5/16, Монолитно-кирпичный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",Дизайнерский,25 25 20 25,NaN,На улицу и двор,"Совмещенный (2), Раздельный (1)",Можно с детьми,3.5,"Пасс (1), Груз (1)",Нет
2,271173086,"4, Оба варианта",м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0/116.0/4.0,5/16,подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",Евроремонт,NaN,NaN,На улицу и двор,Совмещенный (3),Можно с детьми,3.2,Пасс (1),NaN

### Переименовываем колонки на английский

In [10]:
df = df.rename(columns={'ID  объявления': 'ad_id',
    'Количество комнат': 'num_rooms',
    'Метро': 'metro',
    'Адрес': 'address',
    'Площадь, м2': 'area_m2',
    'Дом': 'building',
    'Парковка': 'parking',
    'Цена': 'price',
    'Ремонт': 'renovation',
    'Площадь комнат, м2': 'room_area_m2',
    'Балкон': 'balcony',
    'Окна': 'windows',
    'Санузел': 'bathroom',
    'Можно с детьми/животными': 'pets_children_allowed',
    'Высота потолков, м': 'ceiling_height_m',
    'Лифт': 'elevator',
    'Мусоропровод': 'garbage_chute'})
df.head(3)

,ad_id,num_rooms,metro,address,area_m2,building,parking,price,renovation,room_area_m2,balcony,windows,bathroom,pets_children_allowed,ceiling_height_m,elevator,garbage_chute
0,271271157,4,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0/20.0,"5/16, Монолитный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",Дизайнерский,NaN,NaN,NaN,NaN,"Можно с детьми, Можно с животными",3.0,"Пасс (4), Груз (1)",Да
1,271634126,4,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0/95.0/18.0,"5/16, Монолитно-кирпичный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",Дизайнерский,25 25 20 25,NaN,На улицу и двор,"Совмещенный (2), Раздельный (1)",Можно с детьми,3.5,"Пасс (1), Груз (1)",Нет
2,271173086,"4, Оба варианта",м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0/116.0/4.0,5/16,подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",Евроремонт,NaN,NaN,На улицу и двор,Совмещенный (3),Можно с детьми,3.2,Пасс (1),NaN

In [11]:
df = df.fillna(0)
df.isna().sum()

ad_id                    0
num_rooms                0
metro                    0
address                  0
area_m2                  0
building                 0
parking                  0
price                    0
renovation               0
room_area_m2             0
balcony                  0
windows                  0
bathroom                 0
pets_children_allowed    0
ceiling_height_m         0
elevator                 0
garbage_chute            0
dtype: int64

#### Корректируем значения в колонке "Цена"

In [12]:
# Оставляем только первое число (если их несколько)
df["price"] = df["price"].astype(str).str.extract(r"^(\d+\.\d+|\d+)")[0]

# Преобразуем в float
df["price"] = df["price"].astype(float)

### Корректируем значения в колонке num_rooms и площадь

In [13]:
df["num_rooms"] = df["num_rooms"].astype(str).str.extract(r"(\d+)").astype(float)

# 🟢 Оставляем только первое число в площади
df["area_m2"] = df["area_m2"].astype(str).str.split("/").str[0].astype(float)

In [14]:
df

,ad_id,num_rooms,metro,address,area_m2,building,parking,price,renovation,room_area_m2,balcony,windows,bathroom,pets_children_allowed,ceiling_height_m,elevator,garbage_chute
0,271271157,4.0,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0,"5/16, Монолитный",подземная,500000.0,Дизайнерский,0,0,0,0,"Можно с детьми, Можно с животными",3.00,"Пасс (4), Груз (1)",Да
1,271634126,4.0,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0,"5/16, Монолитно-кирпичный",подземная,500000.0,Дизайнерский,25 25 20 25,0,На улицу и двор,"Совмещенный (2), Раздельный (1)",Можно с детьми,3.50,"Пасс (1), Груз (1)",Нет
2,271173086,4.0,м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0,5/16,подземная,500000.0,Евроремонт,0,0,На улицу и двор,Совмещенный (3),Можно с детьми,3.20,Пасс (1),0
3,272197456,4.0,м. Смоленская (3 мин пешком),"Москва, переулок Плотников, 21С1",170.0,5/6,подземная,400000.0,Евроремонт,14-42-20-19,0,На улицу и двор,Совмещенный (3),Можно с животными,3.20,Пасс (1),0
4,273614615,2.0,м. Арбатская (7 мин пешком),"Москва, улица Новый Арбат, 15",58.0,"12/26, Панельный",0,225000.0,Евроремонт,20 18,0,На улицу и двор,Совмещенный (2),0,3.90,"Пасс (1), Груз (1)",Да
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23363,215565511,0.0,м. Говорово (8 мин пешком),"Москва, Боровское шоссе, 2к7, ш. Боровское (3 ...",35.0,10/14,0,42000.0,Евроремонт,0,Балкон (1),0,Совмещенный (1),0,0.00,"Пасс (1), Груз (1)",0
23364,274654844,1.0,м. Солнцево (7 мин пешком),"Москва, Производственная улица, 8к1, ш. Боровс...",38.7,"5/18, Монолитный",0,45000.0,Евроремонт,0,Лоджия (1),Во двор,Совмещенный (1),0,0.00,"Пасс (1), Груз (1)",0
23365,268679909,2.0,м. Солнцево (6 мин пешком),"Москва, Боровский проезд, 11",43.1,"5/5, Кирпичный",0,50000.0,Дизайнерский,0,Балкон (1),На улицу и двор,Совмещенный (1),Можно с детьми,0.00,0,0
23366,274807525,2.0,м. Солнцево (11 мин пешком),"Москва, улица Богданова, 6к1, ш. Боровское (3 ...",52.5,"8/23, Монолитный",наземная,55000.0,Евроремонт,0,Лоджия (1),Во двор,"Совмещенный (1), Раздельный (1)",0,2.65,Пасс (3),Да
23367,274672243,2.0,м. Говорово (10 мин пешком),"Москва, улица Богданова, 2к1, ш. Боровское (3 ...",90.0,"6/23, Панельный",0,57000.0,Косметический,"26,2+15,5-22,0",Лоджия (1),Во двор,Раздельный (1),"Можно с детьми, Можно с животными",0.00,Пасс (3),Да

In [15]:
# Повторная загрузка библиотек после сброса состояния
from sklearn.preprocessing import LabelEncoder

# 🔹 2. Находим категориальные колонки (строковые данные)
categorical_columns = df.select_dtypes(include=["object"]).columns

# 🔹 3. Приводим все категориальные признаки к строковому типу (чтобы избежать смешанных типов)
df[categorical_columns] = df[categorical_columns].astype(str)

# 🔹 4. Кодируем категориальные признаки с помощью LabelEncoder
label_encoders = {}  # Словарь для сохранения энкодеров

for col in categorical_columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])  # Кодируем столбец
    label_encoders[col] = le  # Сохраняем encoder для возможного обратного преобразования

df

,ad_id,num_rooms,metro,address,area_m2,building,parking,price,renovation,room_area_m2,balcony,windows,bathroom,pets_children_allowed,ceiling_height_m,elevator,garbage_chute
0,271271157,4.0,3688,9598,200.0,1772,5,500000.0,2,2,0,0,0,2,3.00,23,1
1,271634126,4.0,3687,9598,198.0,1771,5,500000.0,2,2312,0,3,10,1,3.50,8,2
2,271173086,4.0,3686,9598,200.0,1768,5,500000.0,3,2,0,3,14,1,3.20,7,0
3,272197456,4.0,3682,7234,170.0,1849,5,400000.0,3,514,0,3,14,3,3.20,7,0
4,273614615,2.0,203,9595,58.0,372,0,225000.0,3,1613,0,3,9,0,3.90,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23363,215565511,0.0,971,1374,35.0,106,0,42000.0,3,2,1,0,5,0,0.00,8,0
23364,274654844,1.0,3776,5114,38.7,1782,0,45000.0,3,2,15,1,5,0,0.00,8,0
23365,268679909,2.0,3775,1351,43.1,1842,0,50000.0,2,2,1,3,5,1,0.00,0,0
23366,274807525,2.0,3759,8055,52.5,2236,3,55000.0,3,2,15,1,6,0,2.65,18,1
23367,274672243,2.0,957,8048,90.0,1966,0,57000.0,4,2456,15,1,1,2,0.00,18,1

In [16]:
df.drop_duplicates(inplace=True)

In [18]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.preprocessing import StandardScaler

# ✅ Подготовка данных (используем уже предобработанный df)

# 🔹 Разделяем признаки (X) и целевую переменную (y)
X = df.drop(columns=['price'])  # Убираем целевую переменную из признаков
y = df['price']

# 🔹 Разделяем данные на тренировочную и тестовую выборки (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ✅ Нормализация данных (масштабирование)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 📌 Создание и обучение модели XGBoost
model = xgb.XGBRegressor(
    objective='reg:squarederror',  # Оптимизация MSE
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42
)

# 🔹 Обучаем модель
model.fit(X_train_scaled, y_train)

# ✅ Делаем предсказания
y_pred = model.predict(X_test_scaled)

# 🔹 Вычисляем MAPE
mape = mean_absolute_percentage_error(y_test, y_pred)

# 📌 Вывод результата
print(f"📊 MAPE модели XGBoost: {mape:.2%}")

📊 MAPE модели XGBoost: 23.52%

In [62]:
df.to_csv("boevue_susliki_data.csv", index=False, encoding="utf-8")